### PR TITLE
Blackjack in Java

### PR DESCRIPTION
**Pull request by dave-burke**
The skill-collectors org will be working on this during the next couple of weeks.

### CODE REVIEW

**Comment by coding-horror** [comment]
Excellent so far! LMK when it's ready to merge! 🤜💥🤛

**Comment by pcholt** [comment]
Hey, don't forget to add a build script to buildJvm! :wink:

**Review by pcholt — APPROVED** [review]

**Comment by pcholt** [comment]
Thanks for the addition to buildJvm. My intention was to approve only the buildJvm changes, not the whole PR.

**Comment by coding-horror** [comment]
still ongoiong?

**Comment by dave-burke** [comment]
@coding-horror Yes, but getting close! We meet over lunch on Tuesdays and Fridays to work on it. I think that all we have left is the logic to play the dealer's hand, and then a final review to clean up any remaining bugs etc.

**Comment by dave-burke** [comment]
@coding-horror We are going to do some more testing over the weekend and plan to remove the draft status on Tuesday. The code is "done" though so feel free to take a look and let us know if you have any feedback.

**Comment by dave-burke** [comment]
@coding-horror We're ready for this to be merged! Let us know if you need us to add/change anything.

**Comment by coding-horror** [comment]
looks good! thank you!

**Pull request merged**
