### PR TITLE
Resolve Issue #809

### PR DESCRIPTION
**Pull request by AnthonyMichaelTDM**
#809 brought to my attention that I had mistakenly pushed the same code to two games (pushed 91_train to 91_train and 92_trap), this PR removes the rust implementation of 92_trap (which was really just 91_train), I'll probably contribute an actual implementation of 92_trap soon.

Sorry about this, but glad it's fixed now :)

### CODE REVIEW

**Comment by AnthonyMichaelTDM** [comment]
No worries, I was gonna do it later today so I haven't started yet, can you @ mention me in the pr so I can update #595 when you get it done?

**Comment by coding-horror** [comment]
Oops, I created conflicts. My bad!

**Comment by AnthonyMichaelTDM** [comment]
no worries, given that the PR that created the conflict also fixes this issue, I'd say it's safe to just close this PR

**Comment by ugurkupeli** [comment]
> No worries, I was gonna do it later today so I haven't started yet, can you @ mention me in the pr so I can update #595 when you get it done?

Sure thing, I will do that in the future. The 92 Trap PR is complete

**Pull request closed without merging**
