### PR TITLE
Further change Acey Ducey JavaScript

### PR DESCRIPTION
**Pull request by LukasMurdock**
#332 implemented many of the same things I was thinking of implementing for Acey_Ducey [here](https://github.com/LukasMurdock/basic-computer-games/blob/main/01_Acey_Ducey/javascript/aceyducey.js).

Notable further changes from 332:
- Removed modules—brought utility functions back into `aceyducey.js` to support local HTML without web server—reference in [issue 117](https://github.com/coding-horror/basic-computer-games/issues/117#issuecomment-1003640068)
- Moved back into a `main()`
- Added support for Node.js by checking for window object in `print()` and `input()`
- Added `newGameCards()` to:
  1. Generate three new random cards
  2. Handle the loop that ensures cardOne is less than or equal to cardTwo
  2. Use ES6 array destructuring assignment to return and assign cards
      - `let [cardOne, cardTwo, cardThree] = getGameCards();`
- Added [Prettier](https://prettier.io/) configuration file for code formatting
- Added some comments
- Created utility functions to easily validate yes//no input strings (This does feel like an abstraction taken a tad too far—or just the verbosity of the naming makes it seem more complex than it is)
- Removed `printCard()` and added `getCardValue()` than can be passed into the regular print function
  - Added Nullish Coalescing Operator (`??`) to handle the undefined face value table lookup

### CODE REVIEW

**Comment by domenic** [comment]
It's pretty discouraging to see some of the changes I made undone in this manner. I won't be contributing to this repo anymore.

**Comment by coding-horror** [comment]
Ah, sorry about that @domenic perhaps there can be two implementations in the same folder, if there is disagreement about the approach?

**Comment by LukasMurdock** [comment]
@domenic I apologize for undoing your changes in this manner. I don’t consider myself a pronounced programmer, and I was quite warmed to see that I thought of the same solutions for parts of acey_duey—that was genuinely fun and validating to see.

I never intended any of these changes to be prescriptive—I just wanted to possibly partake in moving the project forward. I agree, the coding changes here did go far in a (this-is-how-to-do-it) manner—not any of which I am set on, yet overwrote your changes in merge:
- Modules or scripts?
- Should we use Prettier? Is so, what configuration?
- What platforms should we support? Should we support Node.js?
- Are the “utility” functions I wrote even worthwhile?
- Let or const?

Some of these questions surfaced in the JavaScript rendering target issue, and I would love to have your feedback on how we can better move forward here—as I greatly appreciate your contributions. I am new to all things here and I would further appreciate if you could show me a better way to contribute code before such prior questions are answered—without stepping on toes like what just happened here.

I do hope that you can still find fun in contributing to this repo.

**Comment by coding-horror** [comment]
Maybe we have a dedicated topic for discussing the JS framework / approaches to use for each program?

**Pull request merged**
