### PR TITLE
Implement 35 Even Wins with Rust

### PR DESCRIPTION
**Pull request by alingse**
This one is simple

I will open another pr later to add some check_rust.yaml to enable github ci  check all implement is ok.

### CODE REVIEW

**Comment by alingse** [comment]
cc @coding-horror  @AnthonyMichaelTDM

**Comment by coding-horror** [comment]
Looks good thank you!

**Comment by AnthonyMichaelTDM** [comment]
missing readme

**Comment by alingse** [comment]
> missing readme

ok, I will add it

**Pull request merged**
