### PR TITLE
javascript node.js scripts

### PR DESCRIPTION
**Pull request by mojoaxel**
These games are meant as simple CLI scripts (see https://github.com/coding-horror/basic-computer-games/issues/117#issuecomment-1070918597).
I therefor think **javascript should target mainly node.js instead of the browser** (in opposite of whats currents implemented).

* So, I started porting the existing javascript implementations to be **simple node-scripts**.
* I also introduced **very basic common function** like `print`, `input` and `tab`. (see https://github.com/coding-horror/basic-computer-games/issues/548#issuecomment-1079839924).
* I decided to use **modern ES-modules** instead of the legacy commonCJ node-syntax. That way the scripts can easily load the common function (also in the browser). For this to work the files have a `*.mjs` extension.
* To not loose the ability to [play the games in the browser](https://coding-horror.github.io/basic-computer-games/) I created a simple node-terminal-emulator that lets **run our node-scripts directly in the browser**. For this to work I overwrote the default process.stdout/stdin of node and hocked them up to some browser mockups. I know this is very hacky but it works just fine (at least for the simple scripts I've tested).

Here is an example of the emulator in action: https://mojoaxel.github.io/basic-computer-games/00_Common/javascript/WebTerminal/terminal.html#74_Rock_Scissors_Paper/javascript/rockscissors.mjs

This way we have the best of both worlds:
* ✔️ The JavaScript implementations get very slim and easy to ready also for beginners. All the browser-specific stuff is gone!
* ✔️ The scripts can simply be executed and played in every shell, just like e.g. the python or perl implementations.
* ✔️ We still have the possibility to run the games in the browser.
* ✔️ The terminal-emulator even feels more "real" because the input fields are gone.
* ❌ It is no longer super easy for the user to run the games locally IN THE BROWSER, but I think that is ok ant it is still possible using the emulator.

The following games already have been refactored to be valid node-script:
* 57_Literature_Quiz
* 74_Rock_Scissors_Paper
* 78_Sine_Wave
* 96_Word
* _all other games still use the existing html-implementation_

_Please let me know what you think!!_

### CODE REVIEW

**Comment by coding-horror** [comment]
As long as we can run the games in the browser for the JS versions, it's all good to me!

**Comment by mojoaxel** [comment]
@nanochess @stevebosman What do you think about this (big) change! I would be happy to hear your input!

**Comment by coding-horror** [comment]
LGTM! Let's merge it and then discuss!

**Comment by mojoaxel** [comment]
Thanks for merging! Looks like the new node.js-terminal-emulator works:
https://coding-horror.github.io/basic-computer-games/00_Common/javascript/WebTerminal/terminal.html#74_Rock_Scissors_Paper/javascript/rockscissors.mjs

**Comment by coding-horror** [comment]
It is good! One thing I noticed, the terminal style seems to disppear if you make the browser narrow, e.g.:

image

compare to a little bit wider:

image

**Pull request merged**
