### PR TITLE
Add script to find missing implementations

### PR DESCRIPTION
**Pull request by joshgrib**
Offshoot of #367

I made this for myself but seems like it'd be useful for others, feel free to close this out if it's not wanted for whatever reason

Current output:

```
Missing 436 implementations:

Missing languages by game:
02_Amazing: perl, vbnet
03_Animal: pascal, perl, vbnet
04_Awari: pascal, perl, ruby, vbnet
05_Bagels: pascal, vbnet
06_Banner: pascal, perl, ruby
07_Basketball: csharp, java, pascal, perl, python, ruby, vbnet
08_Batnum: pascal, perl, ruby
09_Battle: java, pascal, perl, python, ruby, vbnet
10_Blackjack: java, pascal, perl, python, ruby, vbnet
11_Bombardment: csharp, pascal, perl, vbnet
12_Bombs_Away: csharp, pascal, perl, python, ruby, vbnet
13_Bounce: csharp, pascal, perl, ruby, vbnet
14_Bowling: csharp, pascal, perl, ruby, vbnet
15_Boxing: csharp, pascal, perl, ruby, vbnet
16_Bug: csharp, pascal, perl, python, ruby, vbnet
17_Bullfight: java, pascal, perl, python, ruby, vbnet
18_Bullseye: pascal, python, ruby, vbnet
19_Bunny: csharp, pascal, vbnet
20_Buzzword: pascal, vbnet
21_Calendar: csharp, pascal, perl, python, ruby, vbnet
22_Change: pascal, ruby, vbnet
23_Checkers: csharp, java, pascal, perl, vbnet
24_Chemist: pascal, ruby, vbnet
25_Chief: csharp, pascal, perl, python, ruby, vbnet
26_Chomp: csharp, pascal, perl, ruby, vbnet
27_Civil_War: java, pascal, perl, python, ruby, vbnet
28_Combat: pascal, perl, ruby, vbnet
29_Craps: java, pascal, perl, ruby, vbnet
30_Cube: csharp, java, pascal, perl, ruby, vbnet
31_Depth_Charge: pascal, vbnet
32_Diamond: csharp, pascal, vbnet
33_Dice: pascal, vbnet
34_Digits: csharp, pascal, perl, ruby, vbnet
35_Even_Wins: csharp, java, pascal, perl, python, ruby, vbnet
36_Flip_Flop: csharp, pascal, perl, ruby, vbnet
37_Football: csharp, java, pascal, perl, python, ruby, vbnet
38_Fur_Trader: pascal, perl, ruby, vbnet
39_Golf: java, pascal, perl, python, ruby, vbnet
40_Gomoko: csharp, pascal, perl, python, ruby, vbnet
41_Guess: csharp, pascal, ruby, vbnet
42_Gunner: csharp, pascal, perl, ruby, vbnet
43_Hammurabi: pascal, perl, ruby, vbnet
44_Hangman: pascal, perl, ruby, vbnet
45_Hello: csharp, pascal, ruby, vbnet
46_Hexapawn: java, pascal, perl, ruby, vbnet
47_Hi-Lo: pascal, ruby, vbnet
48_High_IQ: csharp, java, pascal, perl, python, ruby, vbnet
49_Hockey: csharp, java, pascal, perl, python, ruby, vbnet
50_Horserace: csharp, java, pascal, perl, ruby, vbnet
51_Hurkle: pascal, perl, vbnet
52_Kinema: csharp, pascal, ruby, vbnet
53_King: csharp, java, pascal, perl, python, ruby, vbnet
54_Letter: csharp, pascal, ruby, vbnet
55_Life: csharp, java, pascal, perl, vbnet
56_Life_for_Two: csharp, java, pascal, perl, python, ruby, vbnet
57_Literature_Quiz: pascal, ruby, vbnet
58_Love: pascal, ruby, vbnet
59_Lunar_LEM_Rocket: csharp, java, pascal, perl, ruby, vbnet
60_Mastermind: java, pascal, perl, ruby, vbnet
61_Math_Dice: ruby, vbnet
62_Mugwump: pascal, perl, ruby, vbnet
63_Name: java, pascal, ruby, vbnet
64_Nicomachus: csharp, pascal, ruby, vbnet
65_Nim: csharp, java, pascal, perl, python, ruby, vbnet
66_Number: csharp, pascal, ruby, vbnet
67_One_Check: csharp, pascal, perl, python, ruby, vbnet
68_Orbit: csharp, pascal, perl, ruby, vbnet
69_Pizza: csharp, pascal, perl, ruby, vbnet
70_Poetry: csharp, pascal, ruby, vbnet
71_Poker: csharp, java, pascal, perl, python, ruby, vbnet
72_Queen: csharp, java, pascal, perl, python, ruby, vbnet
73_Reverse: csharp, pascal, perl, ruby
74_Rock_Scissors_Paper: pascal, ruby, vbnet
75_Roulette: csharp, java, pascal, perl, python, ruby, vbnet
76_Russian_Roulette: pascal, ruby, vbnet
77_Salvo: csharp, java, pascal, perl, ruby, vbnet
78_Sine_Wave: pascal, vbnet
79_Slalom: csharp, java, pascal, perl, python, ruby, vbnet
80_Slots: csharp, pascal, perl, ruby, vbnet
81_Splat: csharp, java, pascal, perl, ruby, vbnet
82_Stars: pascal, ruby, vbnet
83_Stock_Market: java, pascal, perl, python, ruby, vbnet
84_Super_Star_Trek: java, javascript, pascal, perl, ruby, vbnet
85_Synonym: csharp, pascal, ruby, vbnet
86_Target: pascal, perl, ruby, vbnet
87_3-D_Plot: pascal, vbnet
88_3-D_Tic-Tac-Toe: csharp, java, pascal, perl, ruby, vbnet
89_Tic-Tac-Toe: csharp, pascal, perl, ruby, vbnet
90_Tower: pascal, perl, ruby, vbnet
91_Train: pascal, vbnet
92_Trap: csharp, pascal, ruby, vbnet
93_23_Matches: csharp, pascal, perl, ruby, vbnet
94_War: pascal, ruby, vbnet
95_Weekday: csharp, pascal, perl, ruby, vbnet
96_Word: pascal

By language:
perl: 64 missing
vbnet: 91 missing
pascal: 93 missing
ruby: 79 missing
csharp: 52 missing
java: 31 missing
python: 25 missing
javascript: 1 missing
```

### CODE REVIEW

**Comment by coding-horror** [comment]
Looks much better!! Great idea, not sure where to put it.. maybe check in a utilities folder (use numbering so it sorts to the top like `00_Utilities`, then a csharp folder underneath that?

**Comment by zspitz** [comment]
Perhaps the script could be tweaked to create a Markdown table or GitHub task list which could then be pasted as a GH issue.

**Comment by coding-horror** [comment]
sorry, I can't quite tell where this is going.. did we create a `00_utilities` folder?

**Comment by zspitz** [comment]
Question: is the longer list a list of missing implementations? Or of existing implementations?

**Comment by LittleTealeaf** [comment]
> Question: is the longer list a list of missing implementations? Or of existing implementations?
The longer list looks to be a list by game, the smaller list looks to be by language.

**Comment by coding-horror** [comment]
I wanna merge this but it needs to be in `00_Utilities` folder please 🙏

**Comment by joshgrib** [comment]
Updated to move the file, thanks! I felt like it belonged under some sort of "meta" folder but didn't see an existing one when I made my fork. For clarity this script produces a list of **missing implementations** - i.e. work still remaining to be done. Here's the current output from my branch:

```
$ node find-missing-implementations.js
Missing 444 implementations:

Missing languages by game:
┌────────────────────────┬───────────────────────────────────────────────────────────────┐
│        (index)         │                            Values                             │
├────────────────────────┼───────────────────────────────────────────────────────────────┤
│      00_Utilities      │ 'csharp, java, javascript, pascal, perl, python, ruby, vbnet' │
│       02_Amazing       │                         'perl, vbnet'                         │
│       03_Animal        │                     'pascal, perl, vbnet'                     │
│        04_Awari        │                  'pascal, perl, ruby, vbnet'                  │
│       05_Bagels        │                        'pascal, vbnet'                        │
│       06_Banner        │                     'pascal, perl, ruby'                      │
│     07_Basketball      │       'csharp, java, pascal, perl, python, ruby, vbnet'       │
│       08_Batnum        │                     'pascal, perl, ruby'                      │
│       09_Battle        │           'java, pascal, perl, python, ruby, vbnet'           │
│      10_Blackjack      │           'java, pascal, perl, python, ruby, vbnet'           │
│     11_Bombardment     │                 'csharp, pascal, perl, vbnet'                 │
│     12_Bombs_Away      │          'csharp, pascal, perl, python, ruby, vbnet'          │
│       13_Bounce        │              'csharp, pascal, perl, ruby, vbnet'              │
│       14_Bowling       │              'csharp, pascal, perl, ruby, vbnet'              │
│       15_Boxing        │              'csharp, pascal, perl, ruby, vbnet'              │
│         16_Bug         │          'csharp, pascal, perl, python, ruby, vbnet'          │
│      17_Bullfight      │           'java, pascal, perl, python, ruby, vbnet'           │
│      18_Bullseye       │                 'pascal, python, ruby, vbnet'                 │
│        19_Bunny        │                    'csharp, pascal, vbnet'                    │
│      20_Buzzword       │                        'pascal, vbnet'                        │
│      21_Calendar       │          'csharp, pascal, perl, python, ruby, vbnet'          │
│       22_Change        │                     'pascal, ruby, vbnet'                     │
│      23_Checkers       │              'csharp, java, pascal, perl, vbnet'              │
│       24_Chemist       │                     'pascal, ruby, vbnet'                     │
│        25_Chief        │          'csharp, pascal, perl, python, ruby, vbnet'          │
│        26_Chomp        │              'csharp, pascal, perl, ruby, vbnet'              │
│      27_Civil_War      │           'java, pascal, perl, python, ruby, vbnet'           │
│       28_Combat        │                  'pascal, perl, ruby, vbnet'                  │
│        29_Craps        │               'java, pascal, perl, ruby, vbnet'               │
│        30_Cube         │           'csharp, java, pascal, perl, ruby, vbnet'           │
│    31_Depth_Charge     │                        'pascal, vbnet'                        │
│       32_Diamond       │                    'csharp, pascal, vbnet'                    │
│        33_Dice         │                        'pascal, vbnet'                        │
│       34_Digits        │              'csharp, pascal, perl, ruby, vbnet'              │
│      35_Even_Wins      │       'csharp, java, pascal, perl, python, ruby, vbnet'       │
│      36_Flip_Flop      │              'csharp, pascal, perl, ruby, vbnet'              │
│      37_Football       │       'csharp, java, pascal, perl, python, ruby, vbnet'       │
│     38_Fur_Trader      │                  'pascal, perl, ruby, vbnet'                  │
│        39_Golf         │           'java, pascal, perl, python, ruby, vbnet'           │
│       40_Gomoko        │          'csharp, pascal, perl, python, ruby, vbnet'          │
│        41_Guess        │                 'csharp, pascal, ruby, vbnet'                 │
│       42_Gunner        │              'csharp, pascal, perl, ruby, vbnet'              │
│      43_Hammurabi      │                  'pascal, perl, ruby, vbnet'                  │
│       44_Hangman       │                  'pascal, perl, ruby, vbnet'                  │
│        45_Hello        │                 'csharp, pascal, ruby, vbnet'                 │
│      46_Hexapawn       │               'java, pascal, perl, ruby, vbnet'               │
│        47_Hi-Lo        │                     'pascal, ruby, vbnet'                     │
│       48_High_IQ       │       'csharp, java, pascal, perl, python, ruby, vbnet'       │
│       49_Hockey        │       'csharp, java, pascal, perl, python, ruby, vbnet'       │
│      50_Horserace      │           'csharp, java, pascal, perl, ruby, vbnet'           │
│       51_Hurkle        │                     'pascal, perl, vbnet'                     │
│       52_Kinema        │                 'csharp, pascal, ruby, vbnet'                 │
│        53_King         │       'csharp, java, pascal, perl, python, ruby, vbnet'       │
│       54_Letter        │                 'csharp, pascal, ruby, vbnet'                 │
│        55_Life         │              'csharp, java, pascal, perl, vbnet'              │
│    56_Life_for_Two     │       'csharp, java, pascal, perl, python, ruby, vbnet'       │
│   57_Literature_Quiz   │                     'pascal, ruby, vbnet'                     │
│        58_Love         │                     'pascal, ruby, vbnet'                     │
│  59_Lunar_LEM_Rocket   │           'csharp, java, pascal, perl, ruby, vbnet'           │
│     60_Mastermind      │               'java, pascal, perl, ruby, vbnet'               │
│      61_Math_Dice      │                         'ruby, vbnet'                         │
│       62_Mugwump       │                  'pascal, perl, ruby, vbnet'                  │
│        63_Name         │                  'java, pascal, ruby, vbnet'                  │
│     64_Nicomachus      │                 'csharp, pascal, ruby, vbnet'                 │
│         65_Nim         │       'csharp, java, pascal, perl, python, ruby, vbnet'       │
│       66_Number        │                 'csharp, pascal, ruby, vbnet'                 │
│      67_One_Check      │          'csharp, pascal, perl, python, ruby, vbnet'          │
│        68_Orbit        │              'csharp, pascal, perl, ruby, vbnet'              │
│        69_Pizza        │              'csharp, pascal, perl, ruby, vbnet'              │
│       70_Poetry        │                 'csharp, pascal, ruby, vbnet'                 │
│        71_Poker        │       'csharp, java, pascal, perl, python, ruby, vbnet'       │
│        72_Queen        │       'csharp, java, pascal, perl, python, ruby, vbnet'       │
│       73_Reverse       │                 'csharp, pascal, perl, ruby'                  │
│ 74_Rock_Scissors_Paper │                     'pascal, ruby, vbnet'                     │
│      75_Roulette       │       'csharp, java, pascal, perl, python, ruby, vbnet'       │
│  76_Russian_Roulette   │                     'pascal, ruby, vbnet'                     │
│        77_Salvo        │           'csharp, java, pascal, perl, ruby, vbnet'           │
│      78_Sine_Wave      │                  'javascript, pascal, vbnet'                  │
│       79_Slalom        │       'csharp, java, pascal, perl, python, ruby, vbnet'       │
│        80_Slots        │              'csharp, pascal, perl, ruby, vbnet'              │
│        81_Splat        │           'csharp, java, pascal, perl, ruby, vbnet'           │
│        82_Stars        │                     'pascal, ruby, vbnet'                     │
│    83_Stock_Market     │           'java, pascal, perl, python, ruby, vbnet'           │
│   84_Super_Star_Trek   │               'java, pascal, perl, ruby, vbnet'               │
│       85_Synonym       │                 'csharp, pascal, ruby, vbnet'                 │
│       86_Target        │                  'pascal, perl, ruby, vbnet'                  │
│      87_3-D_Plot       │                        'pascal, vbnet'                        │
│   88_3-D_Tic-Tac-Toe   │           'csharp, java, pascal, perl, ruby, vbnet'           │
│     89_Tic-Tac-Toe     │              'csharp, pascal, perl, ruby, vbnet'              │
│        90_Tower        │                  'pascal, perl, ruby, vbnet'                  │
│        91_Train        │                        'pascal, vbnet'                        │
│        92_Trap         │                 'csharp, pascal, ruby, vbnet'                 │
│     93_23_Matches      │              'csharp, pascal, perl, ruby, vbnet'              │
│         94_War         │                     'pascal, ruby, vbnet'                     │
│       95_Weekday       │              'csharp, pascal, perl, ruby, vbnet'              │
│        96_Word         │                           'pascal'                            │
└────────────────────────┴───────────────────────────────────────────────────────────────┘

By language:
┌────────────┬────────┐
│  (index)   │ Values │
├────────────┼────────┤
│   csharp   │   53   │
│    java    │   32   │
│ javascript │   2    │
│   pascal   │   94   │
│    perl    │   65   │
│   python   │   26   │
│    ruby    │   80   │
│   vbnet    │   92   │
└────────────┴────────┘

```

**Comment by joshgrib** [comment]
Just realized it's including the utilities folder, I'll add another commit to fix that

**Comment by coding-horror** [comment]
super helpful thank you! 🙇

**Pull request merged**
