### PR TITLE
Rust port 18_bullseye

### PR DESCRIPTION
**Pull request by AnthonyMichaelTDM**
rust port of 18_bullseye, with a document about conventions for separating things from main.rs to lib.rs

### CODE REVIEW

**Comment by AnthonyMichaelTDM** [comment]
only the last 3 commits are relevant

**Comment by AnthonyMichaelTDM** [comment]
gonna resubmit this, somethings going on

**Comment by AnthonyMichaelTDM** [comment]
okay idk why there are so many commits, must be from when i had to do some funky git stuff to update my fork

**Comment by coding-horror** [comment]
Hmm. I would pull out your changes (grab those specific files), delete the repository, pull the entire repository from GitHub again, then resubmit. I'm uncomfortable accepting a PR that "changes" 200+ files.. I can't even tell what changed by viewing the diffs!

**Comment by AnthonyMichaelTDM** [comment]
Good idea, I'll do that later today

**Pull request closed without merging**
