### PR TITLE
Initial rust port for 82_Stars

### PR DESCRIPTION
**Pull request by jwbruce**
I have two commits which form the initial rust version of 82_Stars.  I hope you find it useful.  There is some very basic error checking, but it could be more robust.  I may add it later. Of course, the original BASIC program had no error checking at all.

I learned to code on my Apple ][c computer in Applesoft BASIC using these games back in the early 1980s.  I find it very satisfying that in my 50s, I am learning to program in rust using the same programs. 

I hope to commit more rust ports as I progress through the language.

Cheers.
JWB

### CODE REVIEW

**Comment by coding-horror** [comment]
Amazing.. thank you! 🌟

**Comment by Jay-0331** [comment]
@coding-horror can you revert the original rust code there is some html in rust folder please check and revert it back to the original rust solution. We can keep both the solutions.
thank you.

**Review by Jay-0331 — COMMENTED** [review]
@jwbruce what is all this html in rust/Cargo.toml , rust/README.ms, rust/src/main.rs

**Comment by coding-horror** [comment]
If there are unnecessary files, send through a PR for removal. I'm not familiar enough with Rust to know what's required.

**Comment by Jay-0331** [comment]
i already sent the PR and it is merged thanks.

**Pull request merged**
