### PR TITLE
fix(amazing): guarantee exit on bottom row of maze

### PR DESCRIPTION
**Pull request by mcdurdin**
This issue only tends to show up on very small mazes (e.g. 2x2, 3x3). It is possible for the algorithm to never generate an exit to the maze. While the algorithm guarantees with the `Z` variable that only one exit will be generated, it does not test for the situation where we just happen to never get the right random value to open an exit on the bottom row.

The resolution I have come up with here is just to check for this before rendering the final result (i.e. `IF Z=0`), and add an exit to a random cell on the bottom row.

I have only updated the original program file -- we probably need to apply the same fix to the other language versions. I discovered this issue originally when I was 12, which was a good few years ago now, so cannot be sure that I have come up with the same solution here as I did then!

### CODE REVIEW

**Comment by coding-horror** [comment]
could you also add a note to the `readme.md` at the top level? merging this now, thank you!!

**Comment by mcdurdin** [comment]
> could you also add a note to the `readme.md` at the top level?

Just confirming, you are asking me to add a note to https://github.com/coding-horror/basic-computer-games/blob/main/README.md and not to https://github.com/coding-horror/basic-computer-games/blob/main/02_Amazing/README.md?

**Comment by coding-horror** [comment]
sorry I meant at the game folder level, since this is a game-specific comment ;)

**Comment by mcdurdin** [comment]
Righto, see #403!

**Pull request merged**
