### PR TITLE
Ported Acey-Ducey to Object Pascal

### PR DESCRIPTION
**Pull request by gcarreno**
Hi Jeff (@coding-horror ),

As promised, Acey-Ducey in Object Pascal.

Many thanks!

Cheers,
Gus

### CODE REVIEW

**Comment by coding-horror** [comment]
I do have some reservations about this, as I'd like the project to focus on modern, living languages?

**Comment by gcarreno** [comment]
Hey Jeff (@coding-horror),

Your kinda getting my blood boiling with this outdated notion of "modern, living languages" about Object Pascal :smiley: 

I would really like that you would substantiate a bit where you get this notion from?
Is it your gut? or is it something more tangible?
I think it would be a disservice to get into a flame war of subjective "My language, Your language", and I can quote TIOBE index if you want, or all the syntax/constructs equivalence to C#, but Object Pascal is definitely not dead, nor is it not modern.

I've left a comment on the Pascal version also.

Cheers,
Gus

**Comment by coding-horror** [comment]
Let me ask you this: are you willing to convert every single sample in this book into Pascal?

If yes, then let's proceed.

If not, then let's stop here.

Does that seem fair?

**Comment by gcarreno** [comment]
Hey Jeff(@coding-horror),

> Let me ask you this: are you willing to convert every single sample in this book into Pascal?

I'm glad you ask!!

It was my plan to plod along at a timely pace, but yes I was willing to get at it until I translated all of them.

AND I'm also planning on getting it under both styles: Pascal and Object Pascal. So yeah, I am committed!

Cheers,
Gus

**Comment by coding-horror** [comment]
Let's keep this discussion at  https://github.com/coding-horror/basic-computer-games/issues/15 for now

**Comment by gcarreno** [comment]
10-4

**Comment by gcarreno** [comment]
You're more inclined on this code being in a parallel repository. Closing.
In context of you wanting to donate, I completely agree.

**Pull request closed without merging**
