### PR TITLE
Classic TicTacToe just in Executable format

### PR DESCRIPTION
**Pull request by ChanderJindal**
First, pick either 'X' or 'O' from the screen then, play the normal one Player TicTacToe.
Playing on Terminal is kinda boring so, I made it into an executable file.

### CODE REVIEW

**Comment by ChanderJindal** [comment]
Hey, I hope .exe files are okay here, if yes I might make more, I mean you gave me the basic structure and all.

**Comment by coding-horror** [comment]
can you create two versions? One basic, emulating the book, and another with a bit more fanciness?

**Comment by AnthonyMichaelTDM** [comment]
I would like to add that having .exe's in a repository without source code and an md5 or sha1 signature is generally frowned upon due to the potential for malware.

**Comment by coding-horror** [comment]
can you resubmit with just the python files, no images or executables please?

**Pull request closed without merging**
