### PR TITLE
75 Roulette in Java

### PR DESCRIPTION
**Pull request by LittleTealeaf**
Going to open this pull request, I'm slightly confused with understanding how the money situation works (with the end of the game, etc.)
Wanted to see if what I wrote was fine or if I misinterpreted from the code listed

### CODE REVIEW

**Comment by coding-horror** [comment]
The best thing to do is test it against the original code, do you have any way of running the original BASIC? I'll commit this for now and you can update it as needed, thank you!

**Comment by LittleTealeaf** [comment]
Not at the moment. I don't have experience actually using BASIC, but I can try to figure it out later. Thanks

**Comment by coding-horror** [comment]
I'm asking on Twitter the best way to verify running these old BASIC progs.

**Comment by LittleTealeaf** [comment]
My go-to has been to try my hand at walking through and understanding the basic code, and look at other language implementations. This one seems a bit more confusing, and probably is going to require me to go in and mark it up a bit on my own to figure out what it's exactly doing.

**Comment by LittleTealeaf** [comment]
@journich Thanks, I'll take a look at that when I get a chance. I'll go back to the programs I've merged previously and try to update those to match the outputs and functionality better, as I believe I got as close as I thought I could, but not exact.

**Comment by journich** [comment]
@LittleTealeaf I've found it much much easier porting the code in conjunction with running the original basic code.  From time to time I even made little changes to the basic code when running it (mostly adding debugging code to print variable values and so on).

**Comment by LittleTealeaf** [comment]
Ok, I changed the output so it more closely mirrors what the original program would say (apart from some small changes, such as adding a space in-between some words that were smushed together).
I think it's currently in a finished state so I will open this up as a pull request

**Comment by LittleTealeaf** [comment]
I know I made a bunch of changes above, I should be all set, unless someone else notices something wrong in my code

**Comment by coding-horror** [comment]
Excellent thank you!!

**Pull request merged**
