### PR TITLE
Python hangman

### PR DESCRIPTION
**Pull request by danielpiron**
Just need to finish up the replaying mechanism. I see there's another hangman PR. I thought my approach to drawing the gallows could be of interest though.

### CODE REVIEW

**Comment by danielpiron** [comment]
So in this case, are we looking to do some sort of merge or is this first come first 'serve'? Gonna leave this up for now in case some of my approach is deemed valuable.

**Comment by coding-horror** [comment]
Bit of a conflict now -- can we try again?

**Comment by coding-horror** [comment]
(I think merging is best, if you have suggestions to make it more readable and clean that's great!)

**Comment by danielpiron** [comment]
This will obviously be opinionated and biased, but I shall adapt the
current version with what I feel are improvements to readability.

**Comment by coding-horror** [comment]
cool! Merging now! 🍺

**Comment by sanstheskeleton50** [comment]
wow dude cool website, and by the way could ya help with my web site because it sucks and here's the link:https://github.com/sanstheskeleton50/gamer-central/blob/main/javascript.yml

**Pull request merged**
