### PR TITLE
fixed typo in 78_Sive_Wave/README.md

### PR DESCRIPTION
**Pull request by JoeStrout**
"on" should have been "of" — confirmed with scan of original article.

### CODE REVIEW

**Comment by AnthonyMichaelTDM** [comment]
This PR does a bit more than advertised, maybe make second PR's to add those 3 games?

**Review by mirkan1 — APPROVED** [review]

**Review by mirkan1 — COMMENTED** [review]
Runtime Error: Too Many Arguments [[line 14](https://miniscript.org/tryit/#)]

https://github.com/coding-horror/basic-computer-games/blob/095617f944471a89eb69a8caf57fc72eb73f0e3b/00_Alternate_Languages/32_Diamond/MiniScript/diamond.ms#L14

is it a miniscript.org thing?

**Review by mirkan1 — APPROVED** [review]

**Review by mirkan1 — CHANGES_REQUESTED** [review]
rewrite diamond.ms again please, [print-statement](https://miniscript.org/wiki/Print) looks like only accepting single input

**Comment by JoeStrout** [comment]
Holy cows, I had no idea all these commits made _after_ submitting my PR were getting added to the PR.

I did not intend to submit these new ports yet.  As @mirkan1 discovered, some of them are using features of MiniScript v1.6, which is not yet released (but will be within a few weeks).  I intend to submit these ports then.

So I guess I'll just close this PR for now.  My apologies for the confusion.

**Pull request closed without merging**
