### PR TITLE
docs: Missing raku language

### PR DESCRIPTION
**Pull request by gcarreno**
On top level README.md there is no mention to the raku language that figures on the source folders

### CODE REVIEW

**Comment by coding-horror** [comment]
Yeah I haven't decided what to do with this one. Looks like a fork of Python? By the TIOBE rules it probably shouldn't be in there by default. Still thinking about this.

**Comment by gcarreno** [comment]
Hey Jeff(@coding-horror),

No probs, whatsoever, Jeff.

I guess assumption is the mother of all effe ups, and I was assuming that it was just a slight overlook.

But yeah, I read the "What's Raku" section on their site and it's a bit too young.
On a joking side note, if you allow Raku and not perl, you have to include Pascal :stuck_out_tongue_closed_eyes: ...
Just kidding, NOT resuming that line of debate again, LOL!!!

When you decide, just drop it like it's hot or merge. I'm cool with either :smile: :hugs: 

Cheers,
Gus

**Comment by coding-horror** [comment]
Totally fine! This is why I soft-launched so we can figure out the issues before I make a big announcement on the blog!

**Comment by gcarreno** [comment]
Cool, cool, thanks!!

**Comment by gcarreno** [comment]
I think I'll close this one and let you ponder your life choices :smile: 
I know you'll figure it out and update the README accordingly :hugs:

**Pull request closed without merging**
