### PR TITLE
make games easy accessable on the web

### PR DESCRIPTION
**Pull request by mojoaxel**
- This PR creates a `index.html` in the root of the repository.
- With this it gets easy to access the games directly in the browser without downloading the repository.
- There is also a new script `00_Utilities/build-index.js`, that creates the index.html for the given folder structure.
- After merging this [github-pages](https://pages.github.com/) can easily be enabled for this repository. (see also #577)
  If we don't want these files in the `main` branch, feel free to merge than into a seperate branch (e.g. `gh-pages`) and only enable github-pages for this branch.)

Here is an example: https://mojoaxel.github.io/basic-computer-games/
image

Open ToDos:
- [x] allowing for one game-folder to have multibel games (html files).
- [ ] create a github action that updates the index.html
- [x] add some basic stylesheet for the html files. (#633)

_What do you think? Any ideas for improvements?_

### CODE REVIEW

**Comment by DLotts** [comment]
OMG, this is awesome!  I was able to check the behavior of my version of Nim against the JavaScript version.  It turns the whole book into a playable website!  I feel so old fashioned with my files and my executables. :-)

**Comment by mojoaxel** [comment]
@coding-horror I think this is ready to be merged
- The failing python pipeline has nothing to do with my changes.
- A github action to auto-regenerate the index.html is still missing, but this could easily be added later.
- I would recommend simply merging this into `main` and than enable github-pages for the main branch. This way everything stays easy and manageable (This is still targeted for beginners!).
- I would feel honored to become a maintainer for this repository, but I'm not promising anything :wink:

**Comment by mojoaxel** [comment]
:tada: https://coding-horror.github.io/basic-computer-games/

**Comment by mojoaxel** [comment]
@coding-horror Could you please add the url as the Website to the repository details.
Also feel free to add me as a maintainer, I'll try to help out with issues and review merge requests.

**Comment by coding-horror** [comment]
Excellent I have added you as a collaborator! Let's see where this goes, I can use the help and deeply appreciate it!

**Pull request merged**
