### PR TITLE
D version of Acey-Ducey.

### PR DESCRIPTION
**Pull request by veelo**
Hi!

Would you accept contributions in other languages than the ones already here?

This is in reaction to https://forum.dlang.org/post/gkdesjcmnbnwwpnzirhi@forum.dlang.org.

Thanks,
Bastiaan.

### CODE REVIEW

**Comment by joshgrib** [comment]
@veelo not a maintainer or anything, but I was just reading [the reasoning for the languages chosen](https://discourse.codinghorror.com/t/updating-101-basic-computer-games-for-2022-and-beyond/7927/34). It seems like `D` would be ruled out by the memory safety constraint. However it appears there is a [memory safe subset of D](https://dlang.org/spec/memory-safe-d.html), called [SafeD](https://dlang.org/articles/safed.html#safed-subset). I don't know D well enough to say, but from a quick skim it seems like this code might already be within the safe subset.

Personally I'm always a fan of "rosetta code" type things so the more the better, and these constraints may have just been for the initial implementations. I just opened [another PR](https://github.com/coding-horror/basic-computer-games/pull/367) adding a note that all implementations are now complete, so might be the perfect time to open it up to other languages!

**Comment by coding-horror** [comment]
Yeah, per wikipedia:

https://en.wikipedia.org/wiki/D_(programming_language)

"The language as a whole is not memory-safe" and thus isn't eligible to be included -- but you are free to link the implementation in alternate languages in the `readme.md` for that game folder!

**Comment by veelo** [comment]
Thanks for looking into this. D as-is is already much more memory-safe than Delphi / Object Pascal (which is in the list of included languages) due to its built-in garbage collector. Of course D also has automatic array bounds checking by default.

On top of that, there is indeed a mechanism to [enforce memory safety](https://dlang.org/spec/memory-safe-d.html) by marking sections or all of the code as `@safe`. This code is then restricted from doing unsafe things that system programming languages need to allow otherwise, such as doing casts that break the type system, modifying pointer values and taking the address of a local variable or function parameter.

At the moment `@safe` D is opt-in. A while back there has been an initiative to make D memory safe by default, which sadly did not come to fruition due to in-consensus on whether imported symbols should be considered safe by default or not.

I did briefly try to mark the code in this PR `@safe`. This did not compile without further changes due to `stdin` not being `@safe`. This is because D `stdin` is a wrapper around a `FILE` object from the C run-time, which is (currently) not considered safe. On a side-note, I assume that many scripting languages that are used in this repository do fall back on the C run-time in much the same manner.

The D-way of dealing with "unsafe" interfaces (i.e., interfaces that cannot be proven to be safe) is to wrap them in `@trusted` functions. This `@trusted` interface must guarantee that the unsafe interface cannot be used in an unsafe manner. Only `@safe` and `@trusted` functions can be called from `@safe` functions . The great advantage of using this approach is that a manual safety audit only needs to consider `@trusted` code, the rest is checked by the compiler.

I did not pursue the `@trusted` fix because it will add some clutter and I consider the current code to be safe also without it. I could have another look though, to see what it would actually look like.

I hope that these considerations give ground to reconsider your verdict :-)

**Comment by coding-horror** [comment]
We are thinking of dropping Pascal for this reason:

https://github.com/coding-horror/basic-computer-games/issues/343

**Comment by veelo** [comment]
> I did not pursue the `@trusted` fix because it will add some clutter and I consider the current code to be safe also without it. I could have another look though, to see what it would actually look like.

Clutter is minimal, and I updated the PR.

**Comment by veelo** [comment]
Great!

**Pull request merged**
