### PR TITLE
Added golang programming language & Acey Ducey game in golang

### PR DESCRIPTION
**Pull request by ibrahimalbarghouthi**

### CODE REVIEW

**Comment by iamtraction** [comment]
According to this answer by Jeff [here](https://discourse.codinghorror.com/t/updating-101-basic-computer-games-for-2021/7927/34), Go isn't one of the languages that this project aims to port to (in this repo, at least).

You should add link to your Go port's fork in the `README`.

**Comment by ibrahimalbarghouthi** [comment]
Thank you @iamtraction for your solution, but according to Jeff's answer Go is considered not memory safe which depends if we're linking C libraries (Which is the case with many memory-safe languages) or using [Unsafe](https://golang.org/pkg/unsafe/) other than that Go compiler will not tolerate unsafe memory access. 

You can check this article [Anything compiled with Golang will not have ASLR/PIE. This is a decision by the language creators as Golang is a secure language, but if the process imports a C library, it exposes itself to possible issues. ](https://insanitybit.github.io/2016/12/28/golang-and-rustlang-memory-safety)

Also this discussion https://news.ycombinator.com/item?id=16675193#:~:text=3%20app...-,Go%20is%20not%20memory%20safe%20(though%20is%20certainly%20safer%20than,leading%20to%20memory%20corruption%2C%20etc.

**Comment by iamtraction** [comment]
I agree with you. I had previously gone through https://blog.stalkr.net/2015/04/golang-data-races-to-break-memory-safety.html and https://research.swtch.com/gorace, so if user doesn't write code that's directly using the `unsafe` package, or creating a data race in a multi-threaded program, Go is very much memory safe.

But it depends if the core maintainers want to allow Go. I would love to port some of these games to Go myself.

**Comment by coding-horror** [comment]
Per the goals of the project, Go is not 100% ironclad memory safe, so the implementations have to be linked from the readme.md.

**Comment by coding-horror** [comment]
I appreciate the effort -- please feel free to repackage this and link from the readme.md in the program folder! Thank you.

**Pull request closed without merging**
