### PR TITLE
Python: Add type annotations

### PR DESCRIPTION
**Pull request by MartinThoma**

### CODE REVIEW

**Comment by mojoaxel** [comment]
Are types realy "a thing" in python?
@uMetalooper @peter-sharp @openback @christopherphan @imiro @bernardcooke53 @sechilds @LittleTealeaf @jbrouwer5 @BillCruise @aviyam @tsmaster @tsmaster What do you think about this?

**Comment by uMetalooper** [comment]
I think it does have effects on your code quality. Make it more verbose I think.

**Comment by LittleTealeaf** [comment]
Take my input with a grain of salt, I'm not like super advanced with python knowledge. However, I suppose given this is a resource, adding type annotations would be helpful for those looking through and learning from this, given that IDEs such as vscode would pick up on the type annotations and provide helpful quick-documentation. 

Unsure if specifying a type restricts usage or adds actual python functionality in itself?

I have recently been trying to include type annotations in my own python scripting rather recently, since it does provide additional help when using my own functions. No idea how it's used in the professional workspace.

**Comment by bernardcooke53** [comment]
Wearing my opinion hat- I don't tend to bother with types when creating little throwaway utilities, but otherwise I've tried to make it muscle memory to type annotate as I go. Types really shine when you run something like mypy on top of a sizeable codebase as it catches sometimes subtle misuse of data types in functions ahead of trying to actually run your code anywhere important. It does affect quality but I think it usually does so positively- can serve as great documentation for almost free. Some tools like pydantic even do data validation based on your annotations!
However in general, unless it's specifically documented then type annotations don't change the way your code runs. To your comment @LittleTealeaf, it doesn't "formally" restrict the usage of your function, I find it better to think of annotations as creating a "convention", similar to how "_private" fields on a class are only private by "convention". A tool like mypy just reports on whether you're following your own conventions or not. You can define a function that takes a string argument and still feed it an integer (at your own peril), and type-hinted or not it will still behave the same. The functionality it adds at runtime is (to my knowledge) population of the `__annotations__` variable which is then a tuple of types. I've never had to hook into it before but I guess it's nice to have and you can probably do some crazy dynamic things with it.

Just like with other Python code, if your types start getting messy you can always create a type variable to represent it- so even though it's more verbose I think it just enhances code quality. Tiny bits of incremental thought go a long way to making a more robust overall program.

@MartinThoma which Python version are you targeting with typing? I contributed with 3.8 but I imagine others are on slightly different versions and I know the builtins/stdlib have gradually had their `__class_getitem__` methods defined for typing, I think this would need a consensus around what versions are ok. Personally I would want to see either 3.7 compatibility (oldest version still in support) or 3.10+ compatibility (learn from the newest release), but ultimately I think that's @coding-horror / another maintainer's call.

**Comment by MartinThoma** [comment]
> Are types realy "a thing" in python?

YES! If you want to read about how to use them: https://medium.com/analytics-vidhya/type-annotations-in-python-3-8-3b401384403d

Please note that Python has gradual typing and the type checker (mypy) is not very strict by default. This helps people / code bases to gradually increase the types. By default, if a function does not have any type annotations in its signature, the body will be ignored. For this reason I introduced many anntations just telling that teh return type is None. It did show some minor issues and one bug, IIRC.

**Comment by MartinThoma** [comment]
> No idea how it's used in the professional workspace.

@LittleTealeaf I've been working as a consultant in Data Science / Machine Learning / Backend Development for several years. In  the past years I have seen more and more type annotations. I have seen more open source projects adding type annotations (but most struggling with supporting older Python versions).

Overall, I'd say: Using type annotations in professional Python development is becoming the standard, especially when support for Python 3.6 or older gets dropped.

When it comes to what should be the case, I see it very similarly as unit tests + documentation. Type annotations are typically less work to add and (considering the necessary work) provide more value.

**Comment by MartinThoma** [comment]
> which Python version are you targeting with typing?

In general, I work most with Python 3.8. We have some features in the basic-computer-games codebase that require Python 3.10, though. I suggest to have a guide on which version we want to have and adjust the CI to check it.

**Comment by MartinThoma** [comment]
For my small private projects, I try to support the latest 3 versions (3.10, 3.9, 3.8 at the moment)

**Comment by bernardcooke53** [comment]
> > which Python version are you targeting with typing?
> 
> In general, I work most with Python 3.8. We have some features in the basic-computer-games codebase that require Python 3.10, though. I suggest to have a guide on which version we want to have and adjust the CI to check it.

I'm still stuck supporting 3.6 code until some services get an updated runtime at my day job. It's a headache, for sure, I'm just glad there's no legacy 2.7 code hanging around. Given for this scale of project there shouldn't be _too_ many backwards-compatibility issues I don't see the harm in asking for 3.7 or 3.8 as the target version.

+1 for the guide on version choice though, given that will probably be an important feature of the book so the reader can get the right tooling set up it would make sense to have a guide on versions for _all_ of the target languages (not just Python).

**Comment by christopherphan** [comment]
I'm not a professional developer (I'm hoping to become one), so take my opinion with a grain of salt. 

I have been type-annotating almost every I write in Python recently. Partly this is because mypy has saved me from errors numerous times. Also, it helps me remember what each argument should be and what type of object is returned. My 2¢ is that this can help novices understand the code better.

**Review by mojoaxel — APPROVED** [review]
since a lot of python contributors here have argued for these types to be added I guess it is a very useful addition!
@MartinThoma Thanks!

**Comment by mojoaxel** [comment]
@coding-horror I would recommend to add @MartinThoma as a co-maintainer (if he is interested). He is a experienced python developer and already contributed a lot to this repository. :1st_place_medal:

**Comment by coding-horror** [comment]
OK! What do you say @MartinThoma ? Do you have time to assist with the project?

**Comment by MartinThoma** [comment]
I'd feel honored to be added as a maintainer 🙏

I'm pretty experienced with Python and I would happily review/support with Python PRs (+ maybe get CI support for other languages, if desired), but for other language PRs I'd rather let other people review them. 

To be transparent: I am on vacation until April and will probably be pretty active until then. It's unclear to me how much time I will have after my vacation.

**Comment by coding-horror** [comment]
OK! I've added you, thank you for your time and assistance!

**Pull request merged**
