### PR TITLE
10. Blackjack in Ruby

### PR DESCRIPTION
**Pull request by AlaaSarhan**

### CODE REVIEW

**Comment by coding-horror** [comment]
Thank you! ♠️♥️♦️♣️

**Comment by coding-horror** [comment]
LMK when this is ready to merge!

**Comment by AlaaSarhan** [comment]
will need some more work before it works .. sorry I got a move going on so still quite busy packing and stuff. Realistically in next 2-3 weeks I should get it working and ready to merge

**Comment by MartinThoma** [comment]
@AlaaSarhan maybe the Python version helps: https://github.com/coding-horror/basic-computer-games/pull/609

**Comment by coding-horror** [comment]
still ongoing?

**Comment by AlaaSarhan** [comment]
Hey, apologies about leaving this hanging this long. Yes I'm working on finishing this this weekend :)

**Comment by MartinThoma** [comment]
Hi @AlaaSarhan , how are things going?

We would like to improve something in the project (see #681 ) on Monday but that would mean for all contributors that they need to fork from the project again.

If you find the time to finish things today, that would be great. Otherwise, I can support you with adjusting your PR after the changes in #681 were applied.

**Comment by AlaaSarhan** [comment]
Hey @MartinThoma

Yeap read about #681. I'm going to work now on this and try to get it to a merge-able working state. If I don't set this to ready to merge by Monday, please go ahead and adjust the history and I can fork/rebase and adjust this PR.

**Comment by AlaaSarhan** [comment]
@MartinThoma okay I think I won't finish this yet, but I'll keep working on it slowly this week to get it to work. So please go ahead with rewriting git history and if I have issues rebasing my fork I'll ask for your help :)

**Comment by MartinThoma** [comment]
Hi @AlaaSarhan , I didn't close this on purpose. This was done automatically when the history was re-written.

I suggest you to do the following:

1. Manually copy the files you worked on
2. Delete your fork on github, delete your local clone of the repository (except for the files you were working on)
3. Fork again, clone again
4. Add your files back; make a new PR

Sorry for the inconvenience.

**Pull request closed without merging**
